//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_KIEM_KE
    {
        public int MaKiemKe { get; set; }
        public int MaSanPham { get; set; }
        public Nullable<int> SoLuongHeThong { get; set; }
        public Nullable<int> SoLuongThucTe { get; set; }
        public Nullable<int> ChenhLech { get; set; }
    
        public virtual KIEM_KE KIEM_KE { get; set; }
        public virtual SAN_PHAM SAN_PHAM { get; set; }
    }
}
