//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KIEM_KE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KIEM_KE()
        {
            this.CHI_TIET_KIEM_KE = new HashSet<CHI_TIET_KIEM_KE>();
        }
    
        public int MaKiemKe { get; set; }
        public Nullable<System.DateTime> NgayKiemKe { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_TIET_KIEM_KE> CHI_TIET_KIEM_KE { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
    }
}
