//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICH_LAM_CONG_VIEC
    {
        public int MaLichCongViec { get; set; }
        public int MaLich { get; set; }
        public int MaCongViec { get; set; }
        public Nullable<System.TimeSpan> TuGio { get; set; }
        public Nullable<System.TimeSpan> DenGio { get; set; }
        public int UuTien { get; set; }
        public string GhiChu { get; set; }
    
        public virtual CONG_VIEC CONG_VIEC { get; set; }
        public virtual LICH_LAM_VIEC LICH_LAM_VIEC { get; set; }
    }
}
