//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICH_LAM_VIEC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LICH_LAM_VIEC()
        {
            this.LICH_LAM_CONG_VIEC = new HashSet<LICH_LAM_CONG_VIEC>();
        }
    
        public int MaLich { get; set; }
        public int MaNhanVien { get; set; }
        public System.DateTime NgayLam { get; set; }
        public Nullable<int> MaCa { get; set; }
        public string TrangThaiCa { get; set; }
        public string LoaiLich { get; set; }
        public Nullable<System.TimeSpan> GioBatDauDuKien { get; set; }
        public Nullable<System.TimeSpan> GioKetThucDuKien { get; set; }
        public Nullable<System.TimeSpan> GioBatDauThucTe { get; set; }
        public Nullable<System.TimeSpan> GioKetThucThucTe { get; set; }
        public string LyDoDieuChinh { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> NguoiCapNhat { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
    
        public virtual CA_LAM_VIEC CA_LAM_VIEC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICH_LAM_CONG_VIEC> LICH_LAM_CONG_VIEC { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN1 { get; set; }
    }
}
