//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CUA_HANG_TIEN_LOI_Entities : DbContext
    {
        public CUA_HANG_TIEN_LOI_Entities()
            : base("name=CUA_HANG_TIEN_LOI_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CA_LAM_VIEC> CA_LAM_VIEC { get; set; }
        public virtual DbSet<CHI_TIET_HOA_DON> CHI_TIET_HOA_DON { get; set; }
        public virtual DbSet<CHI_TIET_NHAP> CHI_TIET_NHAP { get; set; }
        public virtual DbSet<CONG_VIEC> CONG_VIEC { get; set; }
        public virtual DbSet<DANH_MUC> DANH_MUC { get; set; }
        public virtual DbSet<HOA_DON> HOA_DON { get; set; }
        public virtual DbSet<KHACH_HANG> KHACH_HANG { get; set; }
        public virtual DbSet<KHUYEN_MAI> KHUYEN_MAI { get; set; }
        public virtual DbSet<LICH_LAM_CONG_VIEC> LICH_LAM_CONG_VIEC { get; set; }
        public virtual DbSet<LICH_LAM_VIEC> LICH_LAM_VIEC { get; set; }
        public virtual DbSet<NHA_CUNG_CAP> NHA_CUNG_CAP { get; set; }
        public virtual DbSet<NHAN_VIEN> NHAN_VIEN { get; set; }
        public virtual DbSet<PHIEU_NHAP> PHIEU_NHAP { get; set; }
        public virtual DbSet<SAN_PHAM> SAN_PHAM { get; set; }
        public virtual DbSet<VAI_TRO> VAI_TRO { get; set; }
        public virtual DbSet<CHI_TIET_KIEM_KE> CHI_TIET_KIEM_KE { get; set; }
        public virtual DbSet<KIEM_KE> KIEM_KE { get; set; }
    }
}
